In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Name': ["sam","Daniel", "Amy"],
    'Age': [20,30,40],
    'Salary': [10000, 20000, 30000] 
})

In [3]:
df

     Name  Age  Salary
0     sam   20   10000
1  Daniel   30   20000
2     Amy   40   30000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [26]:
df1 = pd.read_csv('Housing.csv')

In [27]:
df1

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,$12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
545,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             546 non-null    str
 1   area              546 non-null    int64
 2   bedrooms          546 non-null    int64
 3   bathrooms         546 non-null    int64
 4   stories           546 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           546 non-null    int64
 11  prefarea          546 non-null    str
 12  furnishingstatus  546 non-null    str
dtypes: int64(5), str(8)
memory usage: 55.6 KB

In [10]:
df1.describe()

               area    bedrooms   bathrooms     stories     parking
count    546.000000  546.000000  546.000000  546.000000  546.000000
mean    5150.998168    2.968864    1.285714    1.805861    0.692308
std     2168.175437    0.742511    0.502158    0.866736    0.861307
min     1650.000000    1.000000    1.000000    1.000000    0.000000
25%     3600.000000    2.000000    1.000000    1.000000    0.000000
50%     4600.000000    3.000000    1.000000    2.000000    0.000000
75%     6360.000000    3.000000    2.000000    2.000000    1.000000
max    16200.000000    6.000000    4.000000    4.000000    3.000000

In [11]:
df1['area']

0      7420
1      8960
2      9960
3      7500
4      7420
       ...
541    3000
542    2400
543    3620
544    2910
545    3850
Name: area, Length: 546, dtype: int64

In [12]:
df1[['area', 'bedrooms']]

     area  bedrooms
0    7420         4
1    8960         4
2    9960         3
3    7500         4
4    7420         4
..    ...       ...
541  3000         2
542  2400         3
543  3620         2
544  2910         3
545  3850         3

[546 rows x 2 columns]

In [14]:
df1.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            1
guestroom           1
basement            1
hotwaterheating     1
airconditioning     1
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [28]:
df1[df1.isnull().any(axis=1)]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
17,8960000,8500,3,2,4,yes,NaN,no,no,yes,2,no,furnished
21,8680000,7155,3,2,1,yes,yes,NaN,no,yes,2,no,unfurnished
25,8540000,6540,4,2,2,yes,yes,yes,NaN,yes,2,yes,furnished
30,8400000,7475,3,2,4,yes,no,no,no,NaN,2,no,unfurnished
493,2800000,2650,3,1,2,NaN,no,yes,no,no,1,no,unfurnished

In [18]:
df1[df1['guestroom'].isnull()]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
17,8960000,8500,3,2,4,yes,NaN,no,no,yes,2,no,furnished

In [20]:
target_cols = ['guestroom','basement']
df1[df1[target_cols].isnull().any(axis=1)]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
17,8960000,8500,3,2,4,yes,NaN,no,no,yes,2,no,furnished
21,8680000,7155,3,2,1,yes,yes,NaN,no,yes,2,no,unfurnished

In [30]:
df_cleaned_column = df1.dropna(axis=1)
df_cleaned_column

,price,area,bedrooms,bathrooms,stories,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,2,yes,furnished
1,$12250000,8960,4,4,4,3,no,furnished
2,12250000,9960,3,2,2,2,yes,semi-furnished
3,12215000,7500,4,2,2,3,yes,furnished
4,11410000,7420,4,1,2,2,no,furnished
...,...,...,...,...,...,...,...,...
541,1820000,3000,2,1,1,2,no,unfurnished
542,1767150,2400,3,1,1,0,no,semi-furnished
543,1750000,3620,2,1,1,0,no,unfurnished
544,1750000,2910,3,1,1,0,no,furnished
545,1750000,3850,3,1,2,0,no,unfurnished

In [29]:
df_cleaned_row  = df1.dropna(axis=0)
df_cleaned_row

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,$12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
545,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [22]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             546 non-null    str
 1   area              546 non-null    int64
 2   bedrooms          546 non-null    int64
 3   bathrooms         546 non-null    int64
 4   stories           546 non-null    int64
 5   parking           546 non-null    int64
 6   prefarea          546 non-null    str
 7   furnishingstatus  546 non-null    str
dtypes: int64(5), str(3)
memory usage: 34.3 KB

In [39]:
df1_query_output = df1.query("bathrooms > 2 and furnishingstatus == 'furnished'")
df1_query_output

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
1,$12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
89,6440000,8580,5,3,2,yes,no,no,no,no,2,no,furnished

In [40]:
df1 = df1.dropna(axis=0)

In [41]:
df1

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,$12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
545,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [42]:
df1.to_csv("housing_clean.csv", index=False)